# Generated by Django 4.1.5 on 2023-01-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customer_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
